package com.core.BasicInformation.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ClassInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public ClassInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andClassNameIsNull() {
			addCriterion("class_name is null");
			return (Criteria) this;
		}

		public Criteria andClassNameIsNotNull() {
			addCriterion("class_name is not null");
			return (Criteria) this;
		}

		public Criteria andClassNameEqualTo(String value) {
			addCriterion("class_name =", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotEqualTo(String value) {
			addCriterion("class_name <>", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameGreaterThan(String value) {
			addCriterion("class_name >", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameGreaterThanOrEqualTo(String value) {
			addCriterion("class_name >=", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameLessThan(String value) {
			addCriterion("class_name <", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameLessThanOrEqualTo(String value) {
			addCriterion("class_name <=", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameLike(String value) {
			addCriterion("class_name like", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotLike(String value) {
			addCriterion("class_name not like", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameIn(List<String> values) {
			addCriterion("class_name in", values, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotIn(List<String> values) {
			addCriterion("class_name not in", values, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameBetween(String value1, String value2) {
			addCriterion("class_name between", value1, value2, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotBetween(String value1, String value2) {
			addCriterion("class_name not between", value1, value2, "className");
			return (Criteria) this;
		}

		public Criteria andPlaceIsNull() {
			addCriterion("place is null");
			return (Criteria) this;
		}

		public Criteria andPlaceIsNotNull() {
			addCriterion("place is not null");
			return (Criteria) this;
		}

		public Criteria andPlaceEqualTo(String value) {
			addCriterion("place =", value, "place");
			return (Criteria) this;
		}

		public Criteria andPlaceNotEqualTo(String value) {
			addCriterion("place <>", value, "place");
			return (Criteria) this;
		}

		public Criteria andPlaceGreaterThan(String value) {
			addCriterion("place >", value, "place");
			return (Criteria) this;
		}

		public Criteria andPlaceGreaterThanOrEqualTo(String value) {
			addCriterion("place >=", value, "place");
			return (Criteria) this;
		}

		public Criteria andPlaceLessThan(String value) {
			addCriterion("place <", value, "place");
			return (Criteria) this;
		}

		public Criteria andPlaceLessThanOrEqualTo(String value) {
			addCriterion("place <=", value, "place");
			return (Criteria) this;
		}

		public Criteria andPlaceLike(String value) {
			addCriterion("place like", value, "place");
			return (Criteria) this;
		}

		public Criteria andPlaceNotLike(String value) {
			addCriterion("place not like", value, "place");
			return (Criteria) this;
		}

		public Criteria andPlaceIn(List<String> values) {
			addCriterion("place in", values, "place");
			return (Criteria) this;
		}

		public Criteria andPlaceNotIn(List<String> values) {
			addCriterion("place not in", values, "place");
			return (Criteria) this;
		}

		public Criteria andPlaceBetween(String value1, String value2) {
			addCriterion("place between", value1, value2, "place");
			return (Criteria) this;
		}

		public Criteria andPlaceNotBetween(String value1, String value2) {
			addCriterion("place not between", value1, value2, "place");
			return (Criteria) this;
		}

		public Criteria andAdmissionTimeIsNull() {
			addCriterion("admission_time is null");
			return (Criteria) this;
		}

		public Criteria andAdmissionTimeIsNotNull() {
			addCriterion("admission_time is not null");
			return (Criteria) this;
		}

		public Criteria andAdmissionTimeEqualTo(Date value) {
			addCriterionForJDBCDate("admission_time =", value, "admissionTime");
			return (Criteria) this;
		}

		public Criteria andAdmissionTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("admission_time <>", value, "admissionTime");
			return (Criteria) this;
		}

		public Criteria andAdmissionTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("admission_time >", value, "admissionTime");
			return (Criteria) this;
		}

		public Criteria andAdmissionTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("admission_time >=", value, "admissionTime");
			return (Criteria) this;
		}

		public Criteria andAdmissionTimeLessThan(Date value) {
			addCriterionForJDBCDate("admission_time <", value, "admissionTime");
			return (Criteria) this;
		}

		public Criteria andAdmissionTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("admission_time <=", value, "admissionTime");
			return (Criteria) this;
		}

		public Criteria andAdmissionTimeIn(List<Date> values) {
			addCriterionForJDBCDate("admission_time in", values,
					"admissionTime");
			return (Criteria) this;
		}

		public Criteria andAdmissionTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("admission_time not in", values,
					"admissionTime");
			return (Criteria) this;
		}

		public Criteria andAdmissionTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("admission_time between", value1, value2,
					"admissionTime");
			return (Criteria) this;
		}

		public Criteria andAdmissionTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("admission_time not between", value1,
					value2, "admissionTime");
			return (Criteria) this;
		}

		public Criteria andProfessionalIsNull() {
			addCriterion("professional is null");
			return (Criteria) this;
		}

		public Criteria andProfessionalIsNotNull() {
			addCriterion("professional is not null");
			return (Criteria) this;
		}

		public Criteria andProfessionalEqualTo(String value) {
			addCriterion("professional =", value, "professional");
			return (Criteria) this;
		}

		public Criteria andProfessionalNotEqualTo(String value) {
			addCriterion("professional <>", value, "professional");
			return (Criteria) this;
		}

		public Criteria andProfessionalGreaterThan(String value) {
			addCriterion("professional >", value, "professional");
			return (Criteria) this;
		}

		public Criteria andProfessionalGreaterThanOrEqualTo(String value) {
			addCriterion("professional >=", value, "professional");
			return (Criteria) this;
		}

		public Criteria andProfessionalLessThan(String value) {
			addCriterion("professional <", value, "professional");
			return (Criteria) this;
		}

		public Criteria andProfessionalLessThanOrEqualTo(String value) {
			addCriterion("professional <=", value, "professional");
			return (Criteria) this;
		}

		public Criteria andProfessionalLike(String value) {
			addCriterion("professional like", value, "professional");
			return (Criteria) this;
		}

		public Criteria andProfessionalNotLike(String value) {
			addCriterion("professional not like", value, "professional");
			return (Criteria) this;
		}

		public Criteria andProfessionalIn(List<String> values) {
			addCriterion("professional in", values, "professional");
			return (Criteria) this;
		}

		public Criteria andProfessionalNotIn(List<String> values) {
			addCriterion("professional not in", values, "professional");
			return (Criteria) this;
		}

		public Criteria andProfessionalBetween(String value1, String value2) {
			addCriterion("professional between", value1, value2, "professional");
			return (Criteria) this;
		}

		public Criteria andProfessionalNotBetween(String value1, String value2) {
			addCriterion("professional not between", value1, value2,
					"professional");
			return (Criteria) this;
		}

		public Criteria andEnrollmentIsNull() {
			addCriterion("enrollment is null");
			return (Criteria) this;
		}

		public Criteria andEnrollmentIsNotNull() {
			addCriterion("enrollment is not null");
			return (Criteria) this;
		}

		public Criteria andEnrollmentEqualTo(Integer value) {
			addCriterion("enrollment =", value, "enrollment");
			return (Criteria) this;
		}

		public Criteria andEnrollmentNotEqualTo(Integer value) {
			addCriterion("enrollment <>", value, "enrollment");
			return (Criteria) this;
		}

		public Criteria andEnrollmentGreaterThan(Integer value) {
			addCriterion("enrollment >", value, "enrollment");
			return (Criteria) this;
		}

		public Criteria andEnrollmentGreaterThanOrEqualTo(Integer value) {
			addCriterion("enrollment >=", value, "enrollment");
			return (Criteria) this;
		}

		public Criteria andEnrollmentLessThan(Integer value) {
			addCriterion("enrollment <", value, "enrollment");
			return (Criteria) this;
		}

		public Criteria andEnrollmentLessThanOrEqualTo(Integer value) {
			addCriterion("enrollment <=", value, "enrollment");
			return (Criteria) this;
		}

		public Criteria andEnrollmentIn(List<Integer> values) {
			addCriterion("enrollment in", values, "enrollment");
			return (Criteria) this;
		}

		public Criteria andEnrollmentNotIn(List<Integer> values) {
			addCriterion("enrollment not in", values, "enrollment");
			return (Criteria) this;
		}

		public Criteria andEnrollmentBetween(Integer value1, Integer value2) {
			addCriterion("enrollment between", value1, value2, "enrollment");
			return (Criteria) this;
		}

		public Criteria andEnrollmentNotBetween(Integer value1, Integer value2) {
			addCriterion("enrollment not between", value1, value2, "enrollment");
			return (Criteria) this;
		}

		public Criteria andTuitionFeesIsNull() {
			addCriterion("tuition_fees is null");
			return (Criteria) this;
		}

		public Criteria andTuitionFeesIsNotNull() {
			addCriterion("tuition_fees is not null");
			return (Criteria) this;
		}

		public Criteria andTuitionFeesEqualTo(Integer value) {
			addCriterion("tuition_fees =", value, "tuitionFees");
			return (Criteria) this;
		}

		public Criteria andTuitionFeesNotEqualTo(Integer value) {
			addCriterion("tuition_fees <>", value, "tuitionFees");
			return (Criteria) this;
		}

		public Criteria andTuitionFeesGreaterThan(Integer value) {
			addCriterion("tuition_fees >", value, "tuitionFees");
			return (Criteria) this;
		}

		public Criteria andTuitionFeesGreaterThanOrEqualTo(Integer value) {
			addCriterion("tuition_fees >=", value, "tuitionFees");
			return (Criteria) this;
		}

		public Criteria andTuitionFeesLessThan(Integer value) {
			addCriterion("tuition_fees <", value, "tuitionFees");
			return (Criteria) this;
		}

		public Criteria andTuitionFeesLessThanOrEqualTo(Integer value) {
			addCriterion("tuition_fees <=", value, "tuitionFees");
			return (Criteria) this;
		}

		public Criteria andTuitionFeesIn(List<Integer> values) {
			addCriterion("tuition_fees in", values, "tuitionFees");
			return (Criteria) this;
		}

		public Criteria andTuitionFeesNotIn(List<Integer> values) {
			addCriterion("tuition_fees not in", values, "tuitionFees");
			return (Criteria) this;
		}

		public Criteria andTuitionFeesBetween(Integer value1, Integer value2) {
			addCriterion("tuition_fees between", value1, value2, "tuitionFees");
			return (Criteria) this;
		}

		public Criteria andTuitionFeesNotBetween(Integer value1, Integer value2) {
			addCriterion("tuition_fees not between", value1, value2,
					"tuitionFees");
			return (Criteria) this;
		}

		public Criteria andTeacherIdIsNull() {
			addCriterion("teacher_id is null");
			return (Criteria) this;
		}

		public Criteria andTeacherIdIsNotNull() {
			addCriterion("teacher_id is not null");
			return (Criteria) this;
		}

		public Criteria andTeacherIdEqualTo(Integer value) {
			addCriterion("teacher_id =", value, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdNotEqualTo(Integer value) {
			addCriterion("teacher_id <>", value, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdGreaterThan(Integer value) {
			addCriterion("teacher_id >", value, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("teacher_id >=", value, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdLessThan(Integer value) {
			addCriterion("teacher_id <", value, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdLessThanOrEqualTo(Integer value) {
			addCriterion("teacher_id <=", value, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdIn(List<Integer> values) {
			addCriterion("teacher_id in", values, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdNotIn(List<Integer> values) {
			addCriterion("teacher_id not in", values, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdBetween(Integer value1, Integer value2) {
			addCriterion("teacher_id between", value1, value2, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdNotBetween(Integer value1, Integer value2) {
			addCriterion("teacher_id not between", value1, value2, "teacherId");
			return (Criteria) this;
		}

		public Criteria andEarlyReplyTimeIsNull() {
			addCriterion("early_reply_time is null");
			return (Criteria) this;
		}

		public Criteria andEarlyReplyTimeIsNotNull() {
			addCriterion("early_reply_time is not null");
			return (Criteria) this;
		}

		public Criteria andEarlyReplyTimeEqualTo(Date value) {
			addCriterionForJDBCDate("early_reply_time =", value,
					"earlyReplyTime");
			return (Criteria) this;
		}

		public Criteria andEarlyReplyTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("early_reply_time <>", value,
					"earlyReplyTime");
			return (Criteria) this;
		}

		public Criteria andEarlyReplyTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("early_reply_time >", value,
					"earlyReplyTime");
			return (Criteria) this;
		}

		public Criteria andEarlyReplyTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("early_reply_time >=", value,
					"earlyReplyTime");
			return (Criteria) this;
		}

		public Criteria andEarlyReplyTimeLessThan(Date value) {
			addCriterionForJDBCDate("early_reply_time <", value,
					"earlyReplyTime");
			return (Criteria) this;
		}

		public Criteria andEarlyReplyTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("early_reply_time <=", value,
					"earlyReplyTime");
			return (Criteria) this;
		}

		public Criteria andEarlyReplyTimeIn(List<Date> values) {
			addCriterionForJDBCDate("early_reply_time in", values,
					"earlyReplyTime");
			return (Criteria) this;
		}

		public Criteria andEarlyReplyTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("early_reply_time not in", values,
					"earlyReplyTime");
			return (Criteria) this;
		}

		public Criteria andEarlyReplyTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("early_reply_time between", value1, value2,
					"earlyReplyTime");
			return (Criteria) this;
		}

		public Criteria andEarlyReplyTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("early_reply_time not between", value1,
					value2, "earlyReplyTime");
			return (Criteria) this;
		}

		public Criteria andLastReplyTimeIsNull() {
			addCriterion("last_reply_time is null");
			return (Criteria) this;
		}

		public Criteria andLastReplyTimeIsNotNull() {
			addCriterion("last_reply_time is not null");
			return (Criteria) this;
		}

		public Criteria andLastReplyTimeEqualTo(Date value) {
			addCriterionForJDBCDate("last_reply_time =", value, "lastReplyTime");
			return (Criteria) this;
		}

		public Criteria andLastReplyTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("last_reply_time <>", value,
					"lastReplyTime");
			return (Criteria) this;
		}

		public Criteria andLastReplyTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("last_reply_time >", value, "lastReplyTime");
			return (Criteria) this;
		}

		public Criteria andLastReplyTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("last_reply_time >=", value,
					"lastReplyTime");
			return (Criteria) this;
		}

		public Criteria andLastReplyTimeLessThan(Date value) {
			addCriterionForJDBCDate("last_reply_time <", value, "lastReplyTime");
			return (Criteria) this;
		}

		public Criteria andLastReplyTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("last_reply_time <=", value,
					"lastReplyTime");
			return (Criteria) this;
		}

		public Criteria andLastReplyTimeIn(List<Date> values) {
			addCriterionForJDBCDate("last_reply_time in", values,
					"lastReplyTime");
			return (Criteria) this;
		}

		public Criteria andLastReplyTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("last_reply_time not in", values,
					"lastReplyTime");
			return (Criteria) this;
		}

		public Criteria andLastReplyTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("last_reply_time between", value1, value2,
					"lastReplyTime");
			return (Criteria) this;
		}

		public Criteria andLastReplyTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("last_reply_time not between", value1,
					value2, "lastReplyTime");
			return (Criteria) this;
		}

		public Criteria andCourseEndYnIsNull() {
			addCriterion("course_end_yn is null");
			return (Criteria) this;
		}

		public Criteria andCourseEndYnIsNotNull() {
			addCriterion("course_end_yn is not null");
			return (Criteria) this;
		}

		public Criteria andCourseEndYnEqualTo(String value) {
			addCriterion("course_end_yn =", value, "courseEndYn");
			return (Criteria) this;
		}

		public Criteria andCourseEndYnNotEqualTo(String value) {
			addCriterion("course_end_yn <>", value, "courseEndYn");
			return (Criteria) this;
		}

		public Criteria andCourseEndYnGreaterThan(String value) {
			addCriterion("course_end_yn >", value, "courseEndYn");
			return (Criteria) this;
		}

		public Criteria andCourseEndYnGreaterThanOrEqualTo(String value) {
			addCriterion("course_end_yn >=", value, "courseEndYn");
			return (Criteria) this;
		}

		public Criteria andCourseEndYnLessThan(String value) {
			addCriterion("course_end_yn <", value, "courseEndYn");
			return (Criteria) this;
		}

		public Criteria andCourseEndYnLessThanOrEqualTo(String value) {
			addCriterion("course_end_yn <=", value, "courseEndYn");
			return (Criteria) this;
		}

		public Criteria andCourseEndYnLike(String value) {
			addCriterion("course_end_yn like", value, "courseEndYn");
			return (Criteria) this;
		}

		public Criteria andCourseEndYnNotLike(String value) {
			addCriterion("course_end_yn not like", value, "courseEndYn");
			return (Criteria) this;
		}

		public Criteria andCourseEndYnIn(List<String> values) {
			addCriterion("course_end_yn in", values, "courseEndYn");
			return (Criteria) this;
		}

		public Criteria andCourseEndYnNotIn(List<String> values) {
			addCriterion("course_end_yn not in", values, "courseEndYn");
			return (Criteria) this;
		}

		public Criteria andCourseEndYnBetween(String value1, String value2) {
			addCriterion("course_end_yn between", value1, value2, "courseEndYn");
			return (Criteria) this;
		}

		public Criteria andCourseEndYnNotBetween(String value1, String value2) {
			addCriterion("course_end_yn not between", value1, value2,
					"courseEndYn");
			return (Criteria) this;
		}

		public Criteria andAppropriateTrainPlanIdIsNull() {
			addCriterion("appropriate_train_plan_id is null");
			return (Criteria) this;
		}

		public Criteria andAppropriateTrainPlanIdIsNotNull() {
			addCriterion("appropriate_train_plan_id is not null");
			return (Criteria) this;
		}

		public Criteria andAppropriateTrainPlanIdEqualTo(Integer value) {
			addCriterion("appropriate_train_plan_id =", value,
					"appropriateTrainPlanId");
			return (Criteria) this;
		}

		public Criteria andAppropriateTrainPlanIdNotEqualTo(Integer value) {
			addCriterion("appropriate_train_plan_id <>", value,
					"appropriateTrainPlanId");
			return (Criteria) this;
		}

		public Criteria andAppropriateTrainPlanIdGreaterThan(Integer value) {
			addCriterion("appropriate_train_plan_id >", value,
					"appropriateTrainPlanId");
			return (Criteria) this;
		}

		public Criteria andAppropriateTrainPlanIdGreaterThanOrEqualTo(
				Integer value) {
			addCriterion("appropriate_train_plan_id >=", value,
					"appropriateTrainPlanId");
			return (Criteria) this;
		}

		public Criteria andAppropriateTrainPlanIdLessThan(Integer value) {
			addCriterion("appropriate_train_plan_id <", value,
					"appropriateTrainPlanId");
			return (Criteria) this;
		}

		public Criteria andAppropriateTrainPlanIdLessThanOrEqualTo(Integer value) {
			addCriterion("appropriate_train_plan_id <=", value,
					"appropriateTrainPlanId");
			return (Criteria) this;
		}

		public Criteria andAppropriateTrainPlanIdIn(List<Integer> values) {
			addCriterion("appropriate_train_plan_id in", values,
					"appropriateTrainPlanId");
			return (Criteria) this;
		}

		public Criteria andAppropriateTrainPlanIdNotIn(List<Integer> values) {
			addCriterion("appropriate_train_plan_id not in", values,
					"appropriateTrainPlanId");
			return (Criteria) this;
		}

		public Criteria andAppropriateTrainPlanIdBetween(Integer value1,
				Integer value2) {
			addCriterion("appropriate_train_plan_id between", value1, value2,
					"appropriateTrainPlanId");
			return (Criteria) this;
		}

		public Criteria andAppropriateTrainPlanIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("appropriate_train_plan_id not between", value1,
					value2, "appropriateTrainPlanId");
			return (Criteria) this;
		}

		public Criteria andContactInfoIsNull() {
			addCriterion("contact_info is null");
			return (Criteria) this;
		}

		public Criteria andContactInfoIsNotNull() {
			addCriterion("contact_info is not null");
			return (Criteria) this;
		}

		public Criteria andContactInfoEqualTo(String value) {
			addCriterion("contact_info =", value, "contactInfo");
			return (Criteria) this;
		}

		public Criteria andContactInfoNotEqualTo(String value) {
			addCriterion("contact_info <>", value, "contactInfo");
			return (Criteria) this;
		}

		public Criteria andContactInfoGreaterThan(String value) {
			addCriterion("contact_info >", value, "contactInfo");
			return (Criteria) this;
		}

		public Criteria andContactInfoGreaterThanOrEqualTo(String value) {
			addCriterion("contact_info >=", value, "contactInfo");
			return (Criteria) this;
		}

		public Criteria andContactInfoLessThan(String value) {
			addCriterion("contact_info <", value, "contactInfo");
			return (Criteria) this;
		}

		public Criteria andContactInfoLessThanOrEqualTo(String value) {
			addCriterion("contact_info <=", value, "contactInfo");
			return (Criteria) this;
		}

		public Criteria andContactInfoLike(String value) {
			addCriterion("contact_info like", value, "contactInfo");
			return (Criteria) this;
		}

		public Criteria andContactInfoNotLike(String value) {
			addCriterion("contact_info not like", value, "contactInfo");
			return (Criteria) this;
		}

		public Criteria andContactInfoIn(List<String> values) {
			addCriterion("contact_info in", values, "contactInfo");
			return (Criteria) this;
		}

		public Criteria andContactInfoNotIn(List<String> values) {
			addCriterion("contact_info not in", values, "contactInfo");
			return (Criteria) this;
		}

		public Criteria andContactInfoBetween(String value1, String value2) {
			addCriterion("contact_info between", value1, value2, "contactInfo");
			return (Criteria) this;
		}

		public Criteria andContactInfoNotBetween(String value1, String value2) {
			addCriterion("contact_info not between", value1, value2,
					"contactInfo");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_business_class
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 16 21:15:25 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    private Integer start;
	private Integer limit;
    public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getLimit() {
		return limit;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}
    
    
}