package com.core.BasicInformation.model;

import java.util.Date;

public class ClassInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_class.id
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_class.class_name
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	private String className;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_class.place
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	private String place;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_class.admission_time
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	private Date admissionTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_class.professional
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	private String professional;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_class.enrollment
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	private Integer enrollment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_class.tuition_fees
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	private Integer tuitionFees;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_class.teacher_id
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	private Integer teacherId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_class.early_reply_time
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	private Date earlyReplyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_class.last_reply_time
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	private Date lastReplyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_class.course_end_yn
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	private String courseEndYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_class.appropriate_train_plan_id
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	private Integer appropriateTrainPlanId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_class.contact_info
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	private String contactInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_class.remark
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_class.id
	 * @return  the value of t_business_class.id
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_class.id
	 * @param id  the value for t_business_class.id
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_class.class_name
	 * @return  the value of t_business_class.class_name
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public String getClassName() {
		return className;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_class.class_name
	 * @param className  the value for t_business_class.class_name
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void setClassName(String className) {
		this.className = className == null ? null : className.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_class.place
	 * @return  the value of t_business_class.place
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public String getPlace() {
		return place;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_class.place
	 * @param place  the value for t_business_class.place
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void setPlace(String place) {
		this.place = place == null ? null : place.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_class.admission_time
	 * @return  the value of t_business_class.admission_time
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public Date getAdmissionTime() {
		return admissionTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_class.admission_time
	 * @param admissionTime  the value for t_business_class.admission_time
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void setAdmissionTime(Date admissionTime) {
		this.admissionTime = admissionTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_class.professional
	 * @return  the value of t_business_class.professional
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public String getProfessional() {
		return professional;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_class.professional
	 * @param professional  the value for t_business_class.professional
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void setProfessional(String professional) {
		this.professional = professional == null ? null : professional.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_class.enrollment
	 * @return  the value of t_business_class.enrollment
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public Integer getEnrollment() {
		return enrollment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_class.enrollment
	 * @param enrollment  the value for t_business_class.enrollment
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void setEnrollment(Integer enrollment) {
		this.enrollment = enrollment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_class.tuition_fees
	 * @return  the value of t_business_class.tuition_fees
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public Integer getTuitionFees() {
		return tuitionFees;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_class.tuition_fees
	 * @param tuitionFees  the value for t_business_class.tuition_fees
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void setTuitionFees(Integer tuitionFees) {
		this.tuitionFees = tuitionFees;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_class.teacher_id
	 * @return  the value of t_business_class.teacher_id
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public Integer getTeacherId() {
		return teacherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_class.teacher_id
	 * @param teacherId  the value for t_business_class.teacher_id
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_class.early_reply_time
	 * @return  the value of t_business_class.early_reply_time
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public Date getEarlyReplyTime() {
		return earlyReplyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_class.early_reply_time
	 * @param earlyReplyTime  the value for t_business_class.early_reply_time
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void setEarlyReplyTime(Date earlyReplyTime) {
		this.earlyReplyTime = earlyReplyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_class.last_reply_time
	 * @return  the value of t_business_class.last_reply_time
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public Date getLastReplyTime() {
		return lastReplyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_class.last_reply_time
	 * @param lastReplyTime  the value for t_business_class.last_reply_time
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void setLastReplyTime(Date lastReplyTime) {
		this.lastReplyTime = lastReplyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_class.course_end_yn
	 * @return  the value of t_business_class.course_end_yn
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public String getCourseEndYn() {
		return courseEndYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_class.course_end_yn
	 * @param courseEndYn  the value for t_business_class.course_end_yn
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void setCourseEndYn(String courseEndYn) {
		this.courseEndYn = courseEndYn == null ? null : courseEndYn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_class.appropriate_train_plan_id
	 * @return  the value of t_business_class.appropriate_train_plan_id
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public Integer getAppropriateTrainPlanId() {
		return appropriateTrainPlanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_class.appropriate_train_plan_id
	 * @param appropriateTrainPlanId  the value for t_business_class.appropriate_train_plan_id
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void setAppropriateTrainPlanId(Integer appropriateTrainPlanId) {
		this.appropriateTrainPlanId = appropriateTrainPlanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_class.contact_info
	 * @return  the value of t_business_class.contact_info
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public String getContactInfo() {
		return contactInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_class.contact_info
	 * @param contactInfo  the value for t_business_class.contact_info
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void setContactInfo(String contactInfo) {
		this.contactInfo = contactInfo == null ? null : contactInfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_class.remark
	 * @return  the value of t_business_class.remark
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_class.remark
	 * @param remark  the value for t_business_class.remark
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}