package com.core.BasicInformation.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class StudentInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_business_graduate_student_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_business_graduate_student_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_business_graduate_student_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_graduate_student_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public StudentInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_graduate_student_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_graduate_student_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_graduate_student_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_graduate_student_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_graduate_student_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_graduate_student_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_graduate_student_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_graduate_student_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_graduate_student_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_graduate_student_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_business_graduate_student_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andClassIdIsNull() {
			addCriterion("class_id is null");
			return (Criteria) this;
		}

		public Criteria andClassIdIsNotNull() {
			addCriterion("class_id is not null");
			return (Criteria) this;
		}

		public Criteria andClassIdEqualTo(Integer value) {
			addCriterion("class_id =", value, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdNotEqualTo(Integer value) {
			addCriterion("class_id <>", value, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdGreaterThan(Integer value) {
			addCriterion("class_id >", value, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("class_id >=", value, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdLessThan(Integer value) {
			addCriterion("class_id <", value, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdLessThanOrEqualTo(Integer value) {
			addCriterion("class_id <=", value, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdIn(List<Integer> values) {
			addCriterion("class_id in", values, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdNotIn(List<Integer> values) {
			addCriterion("class_id not in", values, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdBetween(Integer value1, Integer value2) {
			addCriterion("class_id between", value1, value2, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdNotBetween(Integer value1, Integer value2) {
			addCriterion("class_id not between", value1, value2, "classId");
			return (Criteria) this;
		}

		public Criteria andNoIsNull() {
			addCriterion("no is null");
			return (Criteria) this;
		}

		public Criteria andNoIsNotNull() {
			addCriterion("no is not null");
			return (Criteria) this;
		}

		public Criteria andNoEqualTo(String value) {
			addCriterion("no =", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoNotEqualTo(String value) {
			addCriterion("no <>", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoGreaterThan(String value) {
			addCriterion("no >", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoGreaterThanOrEqualTo(String value) {
			addCriterion("no >=", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoLessThan(String value) {
			addCriterion("no <", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoLessThanOrEqualTo(String value) {
			addCriterion("no <=", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoLike(String value) {
			addCriterion("no like", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoNotLike(String value) {
			addCriterion("no not like", value, "no");
			return (Criteria) this;
		}

		public Criteria andNoIn(List<String> values) {
			addCriterion("no in", values, "no");
			return (Criteria) this;
		}

		public Criteria andNoNotIn(List<String> values) {
			addCriterion("no not in", values, "no");
			return (Criteria) this;
		}

		public Criteria andNoBetween(String value1, String value2) {
			addCriterion("no between", value1, value2, "no");
			return (Criteria) this;
		}

		public Criteria andNoNotBetween(String value1, String value2) {
			addCriterion("no not between", value1, value2, "no");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNull() {
			addCriterion("birthday is null");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNotNull() {
			addCriterion("birthday is not null");
			return (Criteria) this;
		}

		public Criteria andBirthdayEqualTo(Date value) {
			addCriterionForJDBCDate("birthday =", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotEqualTo(Date value) {
			addCriterionForJDBCDate("birthday <>", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThan(Date value) {
			addCriterionForJDBCDate("birthday >", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("birthday >=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThan(Date value) {
			addCriterionForJDBCDate("birthday <", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("birthday <=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayIn(List<Date> values) {
			addCriterionForJDBCDate("birthday in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotIn(List<Date> values) {
			addCriterionForJDBCDate("birthday not in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("birthday between", value1, value2,
					"birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("birthday not between", value1, value2,
					"birthday");
			return (Criteria) this;
		}

		public Criteria andIdentityNumIsNull() {
			addCriterion("identity_num is null");
			return (Criteria) this;
		}

		public Criteria andIdentityNumIsNotNull() {
			addCriterion("identity_num is not null");
			return (Criteria) this;
		}

		public Criteria andIdentityNumEqualTo(String value) {
			addCriterion("identity_num =", value, "identityNum");
			return (Criteria) this;
		}

		public Criteria andIdentityNumNotEqualTo(String value) {
			addCriterion("identity_num <>", value, "identityNum");
			return (Criteria) this;
		}

		public Criteria andIdentityNumGreaterThan(String value) {
			addCriterion("identity_num >", value, "identityNum");
			return (Criteria) this;
		}

		public Criteria andIdentityNumGreaterThanOrEqualTo(String value) {
			addCriterion("identity_num >=", value, "identityNum");
			return (Criteria) this;
		}

		public Criteria andIdentityNumLessThan(String value) {
			addCriterion("identity_num <", value, "identityNum");
			return (Criteria) this;
		}

		public Criteria andIdentityNumLessThanOrEqualTo(String value) {
			addCriterion("identity_num <=", value, "identityNum");
			return (Criteria) this;
		}

		public Criteria andIdentityNumLike(String value) {
			addCriterion("identity_num like", value, "identityNum");
			return (Criteria) this;
		}

		public Criteria andIdentityNumNotLike(String value) {
			addCriterion("identity_num not like", value, "identityNum");
			return (Criteria) this;
		}

		public Criteria andIdentityNumIn(List<String> values) {
			addCriterion("identity_num in", values, "identityNum");
			return (Criteria) this;
		}

		public Criteria andIdentityNumNotIn(List<String> values) {
			addCriterion("identity_num not in", values, "identityNum");
			return (Criteria) this;
		}

		public Criteria andIdentityNumBetween(String value1, String value2) {
			addCriterion("identity_num between", value1, value2, "identityNum");
			return (Criteria) this;
		}

		public Criteria andIdentityNumNotBetween(String value1, String value2) {
			addCriterion("identity_num not between", value1, value2,
					"identityNum");
			return (Criteria) this;
		}

		public Criteria andSexIsNull() {
			addCriterion("sex is null");
			return (Criteria) this;
		}

		public Criteria andSexIsNotNull() {
			addCriterion("sex is not null");
			return (Criteria) this;
		}

		public Criteria andSexEqualTo(String value) {
			addCriterion("sex =", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotEqualTo(String value) {
			addCriterion("sex <>", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThan(String value) {
			addCriterion("sex >", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThanOrEqualTo(String value) {
			addCriterion("sex >=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThan(String value) {
			addCriterion("sex <", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThanOrEqualTo(String value) {
			addCriterion("sex <=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLike(String value) {
			addCriterion("sex like", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotLike(String value) {
			addCriterion("sex not like", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexIn(List<String> values) {
			addCriterion("sex in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotIn(List<String> values) {
			addCriterion("sex not in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexBetween(String value1, String value2) {
			addCriterion("sex between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotBetween(String value1, String value2) {
			addCriterion("sex not between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andNationalityIsNull() {
			addCriterion("nationality is null");
			return (Criteria) this;
		}

		public Criteria andNationalityIsNotNull() {
			addCriterion("nationality is not null");
			return (Criteria) this;
		}

		public Criteria andNationalityEqualTo(String value) {
			addCriterion("nationality =", value, "nationality");
			return (Criteria) this;
		}

		public Criteria andNationalityNotEqualTo(String value) {
			addCriterion("nationality <>", value, "nationality");
			return (Criteria) this;
		}

		public Criteria andNationalityGreaterThan(String value) {
			addCriterion("nationality >", value, "nationality");
			return (Criteria) this;
		}

		public Criteria andNationalityGreaterThanOrEqualTo(String value) {
			addCriterion("nationality >=", value, "nationality");
			return (Criteria) this;
		}

		public Criteria andNationalityLessThan(String value) {
			addCriterion("nationality <", value, "nationality");
			return (Criteria) this;
		}

		public Criteria andNationalityLessThanOrEqualTo(String value) {
			addCriterion("nationality <=", value, "nationality");
			return (Criteria) this;
		}

		public Criteria andNationalityLike(String value) {
			addCriterion("nationality like", value, "nationality");
			return (Criteria) this;
		}

		public Criteria andNationalityNotLike(String value) {
			addCriterion("nationality not like", value, "nationality");
			return (Criteria) this;
		}

		public Criteria andNationalityIn(List<String> values) {
			addCriterion("nationality in", values, "nationality");
			return (Criteria) this;
		}

		public Criteria andNationalityNotIn(List<String> values) {
			addCriterion("nationality not in", values, "nationality");
			return (Criteria) this;
		}

		public Criteria andNationalityBetween(String value1, String value2) {
			addCriterion("nationality between", value1, value2, "nationality");
			return (Criteria) this;
		}

		public Criteria andNationalityNotBetween(String value1, String value2) {
			addCriterion("nationality not between", value1, value2,
					"nationality");
			return (Criteria) this;
		}

		public Criteria andWorkUnitIsNull() {
			addCriterion("work_unit is null");
			return (Criteria) this;
		}

		public Criteria andWorkUnitIsNotNull() {
			addCriterion("work_unit is not null");
			return (Criteria) this;
		}

		public Criteria andWorkUnitEqualTo(String value) {
			addCriterion("work_unit =", value, "workUnit");
			return (Criteria) this;
		}

		public Criteria andWorkUnitNotEqualTo(String value) {
			addCriterion("work_unit <>", value, "workUnit");
			return (Criteria) this;
		}

		public Criteria andWorkUnitGreaterThan(String value) {
			addCriterion("work_unit >", value, "workUnit");
			return (Criteria) this;
		}

		public Criteria andWorkUnitGreaterThanOrEqualTo(String value) {
			addCriterion("work_unit >=", value, "workUnit");
			return (Criteria) this;
		}

		public Criteria andWorkUnitLessThan(String value) {
			addCriterion("work_unit <", value, "workUnit");
			return (Criteria) this;
		}

		public Criteria andWorkUnitLessThanOrEqualTo(String value) {
			addCriterion("work_unit <=", value, "workUnit");
			return (Criteria) this;
		}

		public Criteria andWorkUnitLike(String value) {
			addCriterion("work_unit like", value, "workUnit");
			return (Criteria) this;
		}

		public Criteria andWorkUnitNotLike(String value) {
			addCriterion("work_unit not like", value, "workUnit");
			return (Criteria) this;
		}

		public Criteria andWorkUnitIn(List<String> values) {
			addCriterion("work_unit in", values, "workUnit");
			return (Criteria) this;
		}

		public Criteria andWorkUnitNotIn(List<String> values) {
			addCriterion("work_unit not in", values, "workUnit");
			return (Criteria) this;
		}

		public Criteria andWorkUnitBetween(String value1, String value2) {
			addCriterion("work_unit between", value1, value2, "workUnit");
			return (Criteria) this;
		}

		public Criteria andWorkUnitNotBetween(String value1, String value2) {
			addCriterion("work_unit not between", value1, value2, "workUnit");
			return (Criteria) this;
		}

		public Criteria andContactNum1IsNull() {
			addCriterion("contact_num1 is null");
			return (Criteria) this;
		}

		public Criteria andContactNum1IsNotNull() {
			addCriterion("contact_num1 is not null");
			return (Criteria) this;
		}

		public Criteria andContactNum1EqualTo(String value) {
			addCriterion("contact_num1 =", value, "contactNum1");
			return (Criteria) this;
		}

		public Criteria andContactNum1NotEqualTo(String value) {
			addCriterion("contact_num1 <>", value, "contactNum1");
			return (Criteria) this;
		}

		public Criteria andContactNum1GreaterThan(String value) {
			addCriterion("contact_num1 >", value, "contactNum1");
			return (Criteria) this;
		}

		public Criteria andContactNum1GreaterThanOrEqualTo(String value) {
			addCriterion("contact_num1 >=", value, "contactNum1");
			return (Criteria) this;
		}

		public Criteria andContactNum1LessThan(String value) {
			addCriterion("contact_num1 <", value, "contactNum1");
			return (Criteria) this;
		}

		public Criteria andContactNum1LessThanOrEqualTo(String value) {
			addCriterion("contact_num1 <=", value, "contactNum1");
			return (Criteria) this;
		}

		public Criteria andContactNum1Like(String value) {
			addCriterion("contact_num1 like", value, "contactNum1");
			return (Criteria) this;
		}

		public Criteria andContactNum1NotLike(String value) {
			addCriterion("contact_num1 not like", value, "contactNum1");
			return (Criteria) this;
		}

		public Criteria andContactNum1In(List<String> values) {
			addCriterion("contact_num1 in", values, "contactNum1");
			return (Criteria) this;
		}

		public Criteria andContactNum1NotIn(List<String> values) {
			addCriterion("contact_num1 not in", values, "contactNum1");
			return (Criteria) this;
		}

		public Criteria andContactNum1Between(String value1, String value2) {
			addCriterion("contact_num1 between", value1, value2, "contactNum1");
			return (Criteria) this;
		}

		public Criteria andContactNum1NotBetween(String value1, String value2) {
			addCriterion("contact_num1 not between", value1, value2,
					"contactNum1");
			return (Criteria) this;
		}

		public Criteria andContactNum2IsNull() {
			addCriterion("contact_num2 is null");
			return (Criteria) this;
		}

		public Criteria andContactNum2IsNotNull() {
			addCriterion("contact_num2 is not null");
			return (Criteria) this;
		}

		public Criteria andContactNum2EqualTo(String value) {
			addCriterion("contact_num2 =", value, "contactNum2");
			return (Criteria) this;
		}

		public Criteria andContactNum2NotEqualTo(String value) {
			addCriterion("contact_num2 <>", value, "contactNum2");
			return (Criteria) this;
		}

		public Criteria andContactNum2GreaterThan(String value) {
			addCriterion("contact_num2 >", value, "contactNum2");
			return (Criteria) this;
		}

		public Criteria andContactNum2GreaterThanOrEqualTo(String value) {
			addCriterion("contact_num2 >=", value, "contactNum2");
			return (Criteria) this;
		}

		public Criteria andContactNum2LessThan(String value) {
			addCriterion("contact_num2 <", value, "contactNum2");
			return (Criteria) this;
		}

		public Criteria andContactNum2LessThanOrEqualTo(String value) {
			addCriterion("contact_num2 <=", value, "contactNum2");
			return (Criteria) this;
		}

		public Criteria andContactNum2Like(String value) {
			addCriterion("contact_num2 like", value, "contactNum2");
			return (Criteria) this;
		}

		public Criteria andContactNum2NotLike(String value) {
			addCriterion("contact_num2 not like", value, "contactNum2");
			return (Criteria) this;
		}

		public Criteria andContactNum2In(List<String> values) {
			addCriterion("contact_num2 in", values, "contactNum2");
			return (Criteria) this;
		}

		public Criteria andContactNum2NotIn(List<String> values) {
			addCriterion("contact_num2 not in", values, "contactNum2");
			return (Criteria) this;
		}

		public Criteria andContactNum2Between(String value1, String value2) {
			addCriterion("contact_num2 between", value1, value2, "contactNum2");
			return (Criteria) this;
		}

		public Criteria andContactNum2NotBetween(String value1, String value2) {
			addCriterion("contact_num2 not between", value1, value2,
					"contactNum2");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andQqIsNull() {
			addCriterion("qq is null");
			return (Criteria) this;
		}

		public Criteria andQqIsNotNull() {
			addCriterion("qq is not null");
			return (Criteria) this;
		}

		public Criteria andQqEqualTo(String value) {
			addCriterion("qq =", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotEqualTo(String value) {
			addCriterion("qq <>", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqGreaterThan(String value) {
			addCriterion("qq >", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqGreaterThanOrEqualTo(String value) {
			addCriterion("qq >=", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLessThan(String value) {
			addCriterion("qq <", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLessThanOrEqualTo(String value) {
			addCriterion("qq <=", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLike(String value) {
			addCriterion("qq like", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotLike(String value) {
			addCriterion("qq not like", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqIn(List<String> values) {
			addCriterion("qq in", values, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotIn(List<String> values) {
			addCriterion("qq not in", values, "qq");
			return (Criteria) this;
		}

		public Criteria andQqBetween(String value1, String value2) {
			addCriterion("qq between", value1, value2, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotBetween(String value1, String value2) {
			addCriterion("qq not between", value1, value2, "qq");
			return (Criteria) this;
		}

		public Criteria andInvoiceTitleIsNull() {
			addCriterion("invoice_title is null");
			return (Criteria) this;
		}

		public Criteria andInvoiceTitleIsNotNull() {
			addCriterion("invoice_title is not null");
			return (Criteria) this;
		}

		public Criteria andInvoiceTitleEqualTo(String value) {
			addCriterion("invoice_title =", value, "invoiceTitle");
			return (Criteria) this;
		}

		public Criteria andInvoiceTitleNotEqualTo(String value) {
			addCriterion("invoice_title <>", value, "invoiceTitle");
			return (Criteria) this;
		}

		public Criteria andInvoiceTitleGreaterThan(String value) {
			addCriterion("invoice_title >", value, "invoiceTitle");
			return (Criteria) this;
		}

		public Criteria andInvoiceTitleGreaterThanOrEqualTo(String value) {
			addCriterion("invoice_title >=", value, "invoiceTitle");
			return (Criteria) this;
		}

		public Criteria andInvoiceTitleLessThan(String value) {
			addCriterion("invoice_title <", value, "invoiceTitle");
			return (Criteria) this;
		}

		public Criteria andInvoiceTitleLessThanOrEqualTo(String value) {
			addCriterion("invoice_title <=", value, "invoiceTitle");
			return (Criteria) this;
		}

		public Criteria andInvoiceTitleLike(String value) {
			addCriterion("invoice_title like", value, "invoiceTitle");
			return (Criteria) this;
		}

		public Criteria andInvoiceTitleNotLike(String value) {
			addCriterion("invoice_title not like", value, "invoiceTitle");
			return (Criteria) this;
		}

		public Criteria andInvoiceTitleIn(List<String> values) {
			addCriterion("invoice_title in", values, "invoiceTitle");
			return (Criteria) this;
		}

		public Criteria andInvoiceTitleNotIn(List<String> values) {
			addCriterion("invoice_title not in", values, "invoiceTitle");
			return (Criteria) this;
		}

		public Criteria andInvoiceTitleBetween(String value1, String value2) {
			addCriterion("invoice_title between", value1, value2,
					"invoiceTitle");
			return (Criteria) this;
		}

		public Criteria andInvoiceTitleNotBetween(String value1, String value2) {
			addCriterion("invoice_title not between", value1, value2,
					"invoiceTitle");
			return (Criteria) this;
		}

		public Criteria andStudyStatusIsNull() {
			addCriterion("study_status is null");
			return (Criteria) this;
		}

		public Criteria andStudyStatusIsNotNull() {
			addCriterion("study_status is not null");
			return (Criteria) this;
		}

		public Criteria andStudyStatusEqualTo(String value) {
			addCriterion("study_status =", value, "studyStatus");
			return (Criteria) this;
		}

		public Criteria andStudyStatusNotEqualTo(String value) {
			addCriterion("study_status <>", value, "studyStatus");
			return (Criteria) this;
		}

		public Criteria andStudyStatusGreaterThan(String value) {
			addCriterion("study_status >", value, "studyStatus");
			return (Criteria) this;
		}

		public Criteria andStudyStatusGreaterThanOrEqualTo(String value) {
			addCriterion("study_status >=", value, "studyStatus");
			return (Criteria) this;
		}

		public Criteria andStudyStatusLessThan(String value) {
			addCriterion("study_status <", value, "studyStatus");
			return (Criteria) this;
		}

		public Criteria andStudyStatusLessThanOrEqualTo(String value) {
			addCriterion("study_status <=", value, "studyStatus");
			return (Criteria) this;
		}

		public Criteria andStudyStatusLike(String value) {
			addCriterion("study_status like", value, "studyStatus");
			return (Criteria) this;
		}

		public Criteria andStudyStatusNotLike(String value) {
			addCriterion("study_status not like", value, "studyStatus");
			return (Criteria) this;
		}

		public Criteria andStudyStatusIn(List<String> values) {
			addCriterion("study_status in", values, "studyStatus");
			return (Criteria) this;
		}

		public Criteria andStudyStatusNotIn(List<String> values) {
			addCriterion("study_status not in", values, "studyStatus");
			return (Criteria) this;
		}

		public Criteria andStudyStatusBetween(String value1, String value2) {
			addCriterion("study_status between", value1, value2, "studyStatus");
			return (Criteria) this;
		}

		public Criteria andStudyStatusNotBetween(String value1, String value2) {
			addCriterion("study_status not between", value1, value2,
					"studyStatus");
			return (Criteria) this;
		}

		public Criteria andTeacherIdIsNull() {
			addCriterion("teacher_id is null");
			return (Criteria) this;
		}

		public Criteria andTeacherIdIsNotNull() {
			addCriterion("teacher_id is not null");
			return (Criteria) this;
		}

		public Criteria andTeacherIdEqualTo(Integer value) {
			addCriterion("teacher_id =", value, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdNotEqualTo(Integer value) {
			addCriterion("teacher_id <>", value, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdGreaterThan(Integer value) {
			addCriterion("teacher_id >", value, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("teacher_id >=", value, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdLessThan(Integer value) {
			addCriterion("teacher_id <", value, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdLessThanOrEqualTo(Integer value) {
			addCriterion("teacher_id <=", value, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdIn(List<Integer> values) {
			addCriterion("teacher_id in", values, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdNotIn(List<Integer> values) {
			addCriterion("teacher_id not in", values, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdBetween(Integer value1, Integer value2) {
			addCriterion("teacher_id between", value1, value2, "teacherId");
			return (Criteria) this;
		}

		public Criteria andTeacherIdNotBetween(Integer value1, Integer value2) {
			addCriterion("teacher_id not between", value1, value2, "teacherId");
			return (Criteria) this;
		}

		public Criteria andPerformTeacherIdIsNull() {
			addCriterion("perform_teacher_id is null");
			return (Criteria) this;
		}

		public Criteria andPerformTeacherIdIsNotNull() {
			addCriterion("perform_teacher_id is not null");
			return (Criteria) this;
		}

		public Criteria andPerformTeacherIdEqualTo(Integer value) {
			addCriterion("perform_teacher_id =", value, "performTeacherId");
			return (Criteria) this;
		}

		public Criteria andPerformTeacherIdNotEqualTo(Integer value) {
			addCriterion("perform_teacher_id <>", value, "performTeacherId");
			return (Criteria) this;
		}

		public Criteria andPerformTeacherIdGreaterThan(Integer value) {
			addCriterion("perform_teacher_id >", value, "performTeacherId");
			return (Criteria) this;
		}

		public Criteria andPerformTeacherIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("perform_teacher_id >=", value, "performTeacherId");
			return (Criteria) this;
		}

		public Criteria andPerformTeacherIdLessThan(Integer value) {
			addCriterion("perform_teacher_id <", value, "performTeacherId");
			return (Criteria) this;
		}

		public Criteria andPerformTeacherIdLessThanOrEqualTo(Integer value) {
			addCriterion("perform_teacher_id <=", value, "performTeacherId");
			return (Criteria) this;
		}

		public Criteria andPerformTeacherIdIn(List<Integer> values) {
			addCriterion("perform_teacher_id in", values, "performTeacherId");
			return (Criteria) this;
		}

		public Criteria andPerformTeacherIdNotIn(List<Integer> values) {
			addCriterion("perform_teacher_id not in", values,
					"performTeacherId");
			return (Criteria) this;
		}

		public Criteria andPerformTeacherIdBetween(Integer value1,
				Integer value2) {
			addCriterion("perform_teacher_id between", value1, value2,
					"performTeacherId");
			return (Criteria) this;
		}

		public Criteria andPerformTeacherIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("perform_teacher_id not between", value1, value2,
					"performTeacherId");
			return (Criteria) this;
		}

		public Criteria andMentorConfirmationIsNull() {
			addCriterion("mentor_confirmation is null");
			return (Criteria) this;
		}

		public Criteria andMentorConfirmationIsNotNull() {
			addCriterion("mentor_confirmation is not null");
			return (Criteria) this;
		}

		public Criteria andMentorConfirmationEqualTo(String value) {
			addCriterion("mentor_confirmation =", value, "mentorConfirmation");
			return (Criteria) this;
		}

		public Criteria andMentorConfirmationNotEqualTo(String value) {
			addCriterion("mentor_confirmation <>", value, "mentorConfirmation");
			return (Criteria) this;
		}

		public Criteria andMentorConfirmationGreaterThan(String value) {
			addCriterion("mentor_confirmation >", value, "mentorConfirmation");
			return (Criteria) this;
		}

		public Criteria andMentorConfirmationGreaterThanOrEqualTo(String value) {
			addCriterion("mentor_confirmation >=", value, "mentorConfirmation");
			return (Criteria) this;
		}

		public Criteria andMentorConfirmationLessThan(String value) {
			addCriterion("mentor_confirmation <", value, "mentorConfirmation");
			return (Criteria) this;
		}

		public Criteria andMentorConfirmationLessThanOrEqualTo(String value) {
			addCriterion("mentor_confirmation <=", value, "mentorConfirmation");
			return (Criteria) this;
		}

		public Criteria andMentorConfirmationLike(String value) {
			addCriterion("mentor_confirmation like", value,
					"mentorConfirmation");
			return (Criteria) this;
		}

		public Criteria andMentorConfirmationNotLike(String value) {
			addCriterion("mentor_confirmation not like", value,
					"mentorConfirmation");
			return (Criteria) this;
		}

		public Criteria andMentorConfirmationIn(List<String> values) {
			addCriterion("mentor_confirmation in", values, "mentorConfirmation");
			return (Criteria) this;
		}

		public Criteria andMentorConfirmationNotIn(List<String> values) {
			addCriterion("mentor_confirmation not in", values,
					"mentorConfirmation");
			return (Criteria) this;
		}

		public Criteria andMentorConfirmationBetween(String value1,
				String value2) {
			addCriterion("mentor_confirmation between", value1, value2,
					"mentorConfirmation");
			return (Criteria) this;
		}

		public Criteria andMentorConfirmationNotBetween(String value1,
				String value2) {
			addCriterion("mentor_confirmation not between", value1, value2,
					"mentorConfirmation");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanYnIsNull() {
			addCriterion("conform_training_plan_yn is null");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanYnIsNotNull() {
			addCriterion("conform_training_plan_yn is not null");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanYnEqualTo(String value) {
			addCriterion("conform_training_plan_yn =", value,
					"conformTrainingPlanYn");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanYnNotEqualTo(String value) {
			addCriterion("conform_training_plan_yn <>", value,
					"conformTrainingPlanYn");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanYnGreaterThan(String value) {
			addCriterion("conform_training_plan_yn >", value,
					"conformTrainingPlanYn");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanYnGreaterThanOrEqualTo(
				String value) {
			addCriterion("conform_training_plan_yn >=", value,
					"conformTrainingPlanYn");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanYnLessThan(String value) {
			addCriterion("conform_training_plan_yn <", value,
					"conformTrainingPlanYn");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanYnLessThanOrEqualTo(String value) {
			addCriterion("conform_training_plan_yn <=", value,
					"conformTrainingPlanYn");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanYnLike(String value) {
			addCriterion("conform_training_plan_yn like", value,
					"conformTrainingPlanYn");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanYnNotLike(String value) {
			addCriterion("conform_training_plan_yn not like", value,
					"conformTrainingPlanYn");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanYnIn(List<String> values) {
			addCriterion("conform_training_plan_yn in", values,
					"conformTrainingPlanYn");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanYnNotIn(List<String> values) {
			addCriterion("conform_training_plan_yn not in", values,
					"conformTrainingPlanYn");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanYnBetween(String value1,
				String value2) {
			addCriterion("conform_training_plan_yn between", value1, value2,
					"conformTrainingPlanYn");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanYnNotBetween(String value1,
				String value2) {
			addCriterion("conform_training_plan_yn not between", value1,
					value2, "conformTrainingPlanYn");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanInfoIsNull() {
			addCriterion("conform_training_plan_info is null");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanInfoIsNotNull() {
			addCriterion("conform_training_plan_info is not null");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanInfoEqualTo(String value) {
			addCriterion("conform_training_plan_info =", value,
					"conformTrainingPlanInfo");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanInfoNotEqualTo(String value) {
			addCriterion("conform_training_plan_info <>", value,
					"conformTrainingPlanInfo");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanInfoGreaterThan(String value) {
			addCriterion("conform_training_plan_info >", value,
					"conformTrainingPlanInfo");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanInfoGreaterThanOrEqualTo(
				String value) {
			addCriterion("conform_training_plan_info >=", value,
					"conformTrainingPlanInfo");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanInfoLessThan(String value) {
			addCriterion("conform_training_plan_info <", value,
					"conformTrainingPlanInfo");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanInfoLessThanOrEqualTo(String value) {
			addCriterion("conform_training_plan_info <=", value,
					"conformTrainingPlanInfo");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanInfoLike(String value) {
			addCriterion("conform_training_plan_info like", value,
					"conformTrainingPlanInfo");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanInfoNotLike(String value) {
			addCriterion("conform_training_plan_info not like", value,
					"conformTrainingPlanInfo");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanInfoIn(List<String> values) {
			addCriterion("conform_training_plan_info in", values,
					"conformTrainingPlanInfo");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanInfoNotIn(List<String> values) {
			addCriterion("conform_training_plan_info not in", values,
					"conformTrainingPlanInfo");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanInfoBetween(String value1,
				String value2) {
			addCriterion("conform_training_plan_info between", value1, value2,
					"conformTrainingPlanInfo");
			return (Criteria) this;
		}

		public Criteria andConformTrainingPlanInfoNotBetween(String value1,
				String value2) {
			addCriterion("conform_training_plan_info not between", value1,
					value2, "conformTrainingPlanInfo");
			return (Criteria) this;
		}

		public Criteria andSubmitProfessionalEnglishYnIsNull() {
			addCriterion("submit_professional_english_yn is null");
			return (Criteria) this;
		}

		public Criteria andSubmitProfessionalEnglishYnIsNotNull() {
			addCriterion("submit_professional_english_yn is not null");
			return (Criteria) this;
		}

		public Criteria andSubmitProfessionalEnglishYnEqualTo(String value) {
			addCriterion("submit_professional_english_yn =", value,
					"submitProfessionalEnglishYn");
			return (Criteria) this;
		}

		public Criteria andSubmitProfessionalEnglishYnNotEqualTo(String value) {
			addCriterion("submit_professional_english_yn <>", value,
					"submitProfessionalEnglishYn");
			return (Criteria) this;
		}

		public Criteria andSubmitProfessionalEnglishYnGreaterThan(String value) {
			addCriterion("submit_professional_english_yn >", value,
					"submitProfessionalEnglishYn");
			return (Criteria) this;
		}

		public Criteria andSubmitProfessionalEnglishYnGreaterThanOrEqualTo(
				String value) {
			addCriterion("submit_professional_english_yn >=", value,
					"submitProfessionalEnglishYn");
			return (Criteria) this;
		}

		public Criteria andSubmitProfessionalEnglishYnLessThan(String value) {
			addCriterion("submit_professional_english_yn <", value,
					"submitProfessionalEnglishYn");
			return (Criteria) this;
		}

		public Criteria andSubmitProfessionalEnglishYnLessThanOrEqualTo(
				String value) {
			addCriterion("submit_professional_english_yn <=", value,
					"submitProfessionalEnglishYn");
			return (Criteria) this;
		}

		public Criteria andSubmitProfessionalEnglishYnLike(String value) {
			addCriterion("submit_professional_english_yn like", value,
					"submitProfessionalEnglishYn");
			return (Criteria) this;
		}

		public Criteria andSubmitProfessionalEnglishYnNotLike(String value) {
			addCriterion("submit_professional_english_yn not like", value,
					"submitProfessionalEnglishYn");
			return (Criteria) this;
		}

		public Criteria andSubmitProfessionalEnglishYnIn(List<String> values) {
			addCriterion("submit_professional_english_yn in", values,
					"submitProfessionalEnglishYn");
			return (Criteria) this;
		}

		public Criteria andSubmitProfessionalEnglishYnNotIn(List<String> values) {
			addCriterion("submit_professional_english_yn not in", values,
					"submitProfessionalEnglishYn");
			return (Criteria) this;
		}

		public Criteria andSubmitProfessionalEnglishYnBetween(String value1,
				String value2) {
			addCriterion("submit_professional_english_yn between", value1,
					value2, "submitProfessionalEnglishYn");
			return (Criteria) this;
		}

		public Criteria andSubmitProfessionalEnglishYnNotBetween(String value1,
				String value2) {
			addCriterion("submit_professional_english_yn not between", value1,
					value2, "submitProfessionalEnglishYn");
			return (Criteria) this;
		}

		public Criteria andSubmitOpeningReportYnIsNull() {
			addCriterion("submit_opening_report_yn is null");
			return (Criteria) this;
		}

		public Criteria andSubmitOpeningReportYnIsNotNull() {
			addCriterion("submit_opening_report_yn is not null");
			return (Criteria) this;
		}

		public Criteria andSubmitOpeningReportYnEqualTo(String value) {
			addCriterion("submit_opening_report_yn =", value,
					"submitOpeningReportYn");
			return (Criteria) this;
		}

		public Criteria andSubmitOpeningReportYnNotEqualTo(String value) {
			addCriterion("submit_opening_report_yn <>", value,
					"submitOpeningReportYn");
			return (Criteria) this;
		}

		public Criteria andSubmitOpeningReportYnGreaterThan(String value) {
			addCriterion("submit_opening_report_yn >", value,
					"submitOpeningReportYn");
			return (Criteria) this;
		}

		public Criteria andSubmitOpeningReportYnGreaterThanOrEqualTo(
				String value) {
			addCriterion("submit_opening_report_yn >=", value,
					"submitOpeningReportYn");
			return (Criteria) this;
		}

		public Criteria andSubmitOpeningReportYnLessThan(String value) {
			addCriterion("submit_opening_report_yn <", value,
					"submitOpeningReportYn");
			return (Criteria) this;
		}

		public Criteria andSubmitOpeningReportYnLessThanOrEqualTo(String value) {
			addCriterion("submit_opening_report_yn <=", value,
					"submitOpeningReportYn");
			return (Criteria) this;
		}

		public Criteria andSubmitOpeningReportYnLike(String value) {
			addCriterion("submit_opening_report_yn like", value,
					"submitOpeningReportYn");
			return (Criteria) this;
		}

		public Criteria andSubmitOpeningReportYnNotLike(String value) {
			addCriterion("submit_opening_report_yn not like", value,
					"submitOpeningReportYn");
			return (Criteria) this;
		}

		public Criteria andSubmitOpeningReportYnIn(List<String> values) {
			addCriterion("submit_opening_report_yn in", values,
					"submitOpeningReportYn");
			return (Criteria) this;
		}

		public Criteria andSubmitOpeningReportYnNotIn(List<String> values) {
			addCriterion("submit_opening_report_yn not in", values,
					"submitOpeningReportYn");
			return (Criteria) this;
		}

		public Criteria andSubmitOpeningReportYnBetween(String value1,
				String value2) {
			addCriterion("submit_opening_report_yn between", value1, value2,
					"submitOpeningReportYn");
			return (Criteria) this;
		}

		public Criteria andSubmitOpeningReportYnNotBetween(String value1,
				String value2) {
			addCriterion("submit_opening_report_yn not between", value1,
					value2, "submitOpeningReportYn");
			return (Criteria) this;
		}

		public Criteria andSubmitFrontierLectureYnIsNull() {
			addCriterion("submit_frontier_lecture_yn is null");
			return (Criteria) this;
		}

		public Criteria andSubmitFrontierLectureYnIsNotNull() {
			addCriterion("submit_frontier_lecture_yn is not null");
			return (Criteria) this;
		}

		public Criteria andSubmitFrontierLectureYnEqualTo(String value) {
			addCriterion("submit_frontier_lecture_yn =", value,
					"submitFrontierLectureYn");
			return (Criteria) this;
		}

		public Criteria andSubmitFrontierLectureYnNotEqualTo(String value) {
			addCriterion("submit_frontier_lecture_yn <>", value,
					"submitFrontierLectureYn");
			return (Criteria) this;
		}

		public Criteria andSubmitFrontierLectureYnGreaterThan(String value) {
			addCriterion("submit_frontier_lecture_yn >", value,
					"submitFrontierLectureYn");
			return (Criteria) this;
		}

		public Criteria andSubmitFrontierLectureYnGreaterThanOrEqualTo(
				String value) {
			addCriterion("submit_frontier_lecture_yn >=", value,
					"submitFrontierLectureYn");
			return (Criteria) this;
		}

		public Criteria andSubmitFrontierLectureYnLessThan(String value) {
			addCriterion("submit_frontier_lecture_yn <", value,
					"submitFrontierLectureYn");
			return (Criteria) this;
		}

		public Criteria andSubmitFrontierLectureYnLessThanOrEqualTo(String value) {
			addCriterion("submit_frontier_lecture_yn <=", value,
					"submitFrontierLectureYn");
			return (Criteria) this;
		}

		public Criteria andSubmitFrontierLectureYnLike(String value) {
			addCriterion("submit_frontier_lecture_yn like", value,
					"submitFrontierLectureYn");
			return (Criteria) this;
		}

		public Criteria andSubmitFrontierLectureYnNotLike(String value) {
			addCriterion("submit_frontier_lecture_yn not like", value,
					"submitFrontierLectureYn");
			return (Criteria) this;
		}

		public Criteria andSubmitFrontierLectureYnIn(List<String> values) {
			addCriterion("submit_frontier_lecture_yn in", values,
					"submitFrontierLectureYn");
			return (Criteria) this;
		}

		public Criteria andSubmitFrontierLectureYnNotIn(List<String> values) {
			addCriterion("submit_frontier_lecture_yn not in", values,
					"submitFrontierLectureYn");
			return (Criteria) this;
		}

		public Criteria andSubmitFrontierLectureYnBetween(String value1,
				String value2) {
			addCriterion("submit_frontier_lecture_yn between", value1, value2,
					"submitFrontierLectureYn");
			return (Criteria) this;
		}

		public Criteria andSubmitFrontierLectureYnNotBetween(String value1,
				String value2) {
			addCriterion("submit_frontier_lecture_yn not between", value1,
					value2, "submitFrontierLectureYn");
			return (Criteria) this;
		}

		public Criteria andPayTuitionYnIsNull() {
			addCriterion("pay_tuition_yn is null");
			return (Criteria) this;
		}

		public Criteria andPayTuitionYnIsNotNull() {
			addCriterion("pay_tuition_yn is not null");
			return (Criteria) this;
		}

		public Criteria andPayTuitionYnEqualTo(String value) {
			addCriterion("pay_tuition_yn =", value, "payTuitionYn");
			return (Criteria) this;
		}

		public Criteria andPayTuitionYnNotEqualTo(String value) {
			addCriterion("pay_tuition_yn <>", value, "payTuitionYn");
			return (Criteria) this;
		}

		public Criteria andPayTuitionYnGreaterThan(String value) {
			addCriterion("pay_tuition_yn >", value, "payTuitionYn");
			return (Criteria) this;
		}

		public Criteria andPayTuitionYnGreaterThanOrEqualTo(String value) {
			addCriterion("pay_tuition_yn >=", value, "payTuitionYn");
			return (Criteria) this;
		}

		public Criteria andPayTuitionYnLessThan(String value) {
			addCriterion("pay_tuition_yn <", value, "payTuitionYn");
			return (Criteria) this;
		}

		public Criteria andPayTuitionYnLessThanOrEqualTo(String value) {
			addCriterion("pay_tuition_yn <=", value, "payTuitionYn");
			return (Criteria) this;
		}

		public Criteria andPayTuitionYnLike(String value) {
			addCriterion("pay_tuition_yn like", value, "payTuitionYn");
			return (Criteria) this;
		}

		public Criteria andPayTuitionYnNotLike(String value) {
			addCriterion("pay_tuition_yn not like", value, "payTuitionYn");
			return (Criteria) this;
		}

		public Criteria andPayTuitionYnIn(List<String> values) {
			addCriterion("pay_tuition_yn in", values, "payTuitionYn");
			return (Criteria) this;
		}

		public Criteria andPayTuitionYnNotIn(List<String> values) {
			addCriterion("pay_tuition_yn not in", values, "payTuitionYn");
			return (Criteria) this;
		}

		public Criteria andPayTuitionYnBetween(String value1, String value2) {
			addCriterion("pay_tuition_yn between", value1, value2,
					"payTuitionYn");
			return (Criteria) this;
		}

		public Criteria andPayTuitionYnNotBetween(String value1, String value2) {
			addCriterion("pay_tuition_yn not between", value1, value2,
					"payTuitionYn");
			return (Criteria) this;
		}

		public Criteria andNeedPayAmountIsNull() {
			addCriterion("need_pay_amount is null");
			return (Criteria) this;
		}

		public Criteria andNeedPayAmountIsNotNull() {
			addCriterion("need_pay_amount is not null");
			return (Criteria) this;
		}

		public Criteria andNeedPayAmountEqualTo(Integer value) {
			addCriterion("need_pay_amount =", value, "needPayAmount");
			return (Criteria) this;
		}

		public Criteria andNeedPayAmountNotEqualTo(Integer value) {
			addCriterion("need_pay_amount <>", value, "needPayAmount");
			return (Criteria) this;
		}

		public Criteria andNeedPayAmountGreaterThan(Integer value) {
			addCriterion("need_pay_amount >", value, "needPayAmount");
			return (Criteria) this;
		}

		public Criteria andNeedPayAmountGreaterThanOrEqualTo(Integer value) {
			addCriterion("need_pay_amount >=", value, "needPayAmount");
			return (Criteria) this;
		}

		public Criteria andNeedPayAmountLessThan(Integer value) {
			addCriterion("need_pay_amount <", value, "needPayAmount");
			return (Criteria) this;
		}

		public Criteria andNeedPayAmountLessThanOrEqualTo(Integer value) {
			addCriterion("need_pay_amount <=", value, "needPayAmount");
			return (Criteria) this;
		}

		public Criteria andNeedPayAmountIn(List<Integer> values) {
			addCriterion("need_pay_amount in", values, "needPayAmount");
			return (Criteria) this;
		}

		public Criteria andNeedPayAmountNotIn(List<Integer> values) {
			addCriterion("need_pay_amount not in", values, "needPayAmount");
			return (Criteria) this;
		}

		public Criteria andNeedPayAmountBetween(Integer value1, Integer value2) {
			addCriterion("need_pay_amount between", value1, value2,
					"needPayAmount");
			return (Criteria) this;
		}

		public Criteria andNeedPayAmountNotBetween(Integer value1,
				Integer value2) {
			addCriterion("need_pay_amount not between", value1, value2,
					"needPayAmount");
			return (Criteria) this;
		}

		public Criteria andPassPaperReviewYnIsNull() {
			addCriterion("pass_paper_review_yn is null");
			return (Criteria) this;
		}

		public Criteria andPassPaperReviewYnIsNotNull() {
			addCriterion("pass_paper_review_yn is not null");
			return (Criteria) this;
		}

		public Criteria andPassPaperReviewYnEqualTo(String value) {
			addCriterion("pass_paper_review_yn =", value, "passPaperReviewYn");
			return (Criteria) this;
		}

		public Criteria andPassPaperReviewYnNotEqualTo(String value) {
			addCriterion("pass_paper_review_yn <>", value, "passPaperReviewYn");
			return (Criteria) this;
		}

		public Criteria andPassPaperReviewYnGreaterThan(String value) {
			addCriterion("pass_paper_review_yn >", value, "passPaperReviewYn");
			return (Criteria) this;
		}

		public Criteria andPassPaperReviewYnGreaterThanOrEqualTo(String value) {
			addCriterion("pass_paper_review_yn >=", value, "passPaperReviewYn");
			return (Criteria) this;
		}

		public Criteria andPassPaperReviewYnLessThan(String value) {
			addCriterion("pass_paper_review_yn <", value, "passPaperReviewYn");
			return (Criteria) this;
		}

		public Criteria andPassPaperReviewYnLessThanOrEqualTo(String value) {
			addCriterion("pass_paper_review_yn <=", value, "passPaperReviewYn");
			return (Criteria) this;
		}

		public Criteria andPassPaperReviewYnLike(String value) {
			addCriterion("pass_paper_review_yn like", value,
					"passPaperReviewYn");
			return (Criteria) this;
		}

		public Criteria andPassPaperReviewYnNotLike(String value) {
			addCriterion("pass_paper_review_yn not like", value,
					"passPaperReviewYn");
			return (Criteria) this;
		}

		public Criteria andPassPaperReviewYnIn(List<String> values) {
			addCriterion("pass_paper_review_yn in", values, "passPaperReviewYn");
			return (Criteria) this;
		}

		public Criteria andPassPaperReviewYnNotIn(List<String> values) {
			addCriterion("pass_paper_review_yn not in", values,
					"passPaperReviewYn");
			return (Criteria) this;
		}

		public Criteria andPassPaperReviewYnBetween(String value1, String value2) {
			addCriterion("pass_paper_review_yn between", value1, value2,
					"passPaperReviewYn");
			return (Criteria) this;
		}

		public Criteria andPassPaperReviewYnNotBetween(String value1,
				String value2) {
			addCriterion("pass_paper_review_yn not between", value1, value2,
					"passPaperReviewYn");
			return (Criteria) this;
		}

		public Criteria andReplyStatusIsNull() {
			addCriterion("reply_status is null");
			return (Criteria) this;
		}

		public Criteria andReplyStatusIsNotNull() {
			addCriterion("reply_status is not null");
			return (Criteria) this;
		}

		public Criteria andReplyStatusEqualTo(String value) {
			addCriterion("reply_status =", value, "replyStatus");
			return (Criteria) this;
		}

		public Criteria andReplyStatusNotEqualTo(String value) {
			addCriterion("reply_status <>", value, "replyStatus");
			return (Criteria) this;
		}

		public Criteria andReplyStatusGreaterThan(String value) {
			addCriterion("reply_status >", value, "replyStatus");
			return (Criteria) this;
		}

		public Criteria andReplyStatusGreaterThanOrEqualTo(String value) {
			addCriterion("reply_status >=", value, "replyStatus");
			return (Criteria) this;
		}

		public Criteria andReplyStatusLessThan(String value) {
			addCriterion("reply_status <", value, "replyStatus");
			return (Criteria) this;
		}

		public Criteria andReplyStatusLessThanOrEqualTo(String value) {
			addCriterion("reply_status <=", value, "replyStatus");
			return (Criteria) this;
		}

		public Criteria andReplyStatusLike(String value) {
			addCriterion("reply_status like", value, "replyStatus");
			return (Criteria) this;
		}

		public Criteria andReplyStatusNotLike(String value) {
			addCriterion("reply_status not like", value, "replyStatus");
			return (Criteria) this;
		}

		public Criteria andReplyStatusIn(List<String> values) {
			addCriterion("reply_status in", values, "replyStatus");
			return (Criteria) this;
		}

		public Criteria andReplyStatusNotIn(List<String> values) {
			addCriterion("reply_status not in", values, "replyStatus");
			return (Criteria) this;
		}

		public Criteria andReplyStatusBetween(String value1, String value2) {
			addCriterion("reply_status between", value1, value2, "replyStatus");
			return (Criteria) this;
		}

		public Criteria andReplyStatusNotBetween(String value1, String value2) {
			addCriterion("reply_status not between", value1, value2,
					"replyStatus");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_business_graduate_student_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_business_graduate_student_info
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 10 21:26:45 GMT+08:00 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
    private Integer start;
	private Integer limit;
    public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getLimit() {
		return limit;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}
}