package com.core.BasicInformation.model;

import java.util.Date;

public class StudentInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.id
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.class_id
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private Integer classId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.no
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.name
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.birthday
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.identity_num
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String identityNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.sex
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.nationality
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String nationality;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.work_unit
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String workUnit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.contact_num1
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String contactNum1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.contact_num2
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String contactNum2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.email
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.qq
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String qq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.invoice_title
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String invoiceTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.study_status
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String studyStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.teacher_id
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private Integer teacherId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.perform_teacher_id
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private Integer performTeacherId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.mentor_confirmation
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String mentorConfirmation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.remark
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.conform_training_plan_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String conformTrainingPlanYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.conform_training_plan_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String conformTrainingPlanInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.submit_professional_english_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String submitProfessionalEnglishYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.submit_opening_report_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String submitOpeningReportYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.submit_frontier_lecture_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String submitFrontierLectureYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.pay_tuition_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String payTuitionYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.need_pay_amount
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private Integer needPayAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.pass_paper_review_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String passPaperReviewYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_business_graduate_student_info.reply_status
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	private String replyStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.id
	 * @return  the value of t_business_graduate_student_info.id
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.id
	 * @param id  the value for t_business_graduate_student_info.id
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.class_id
	 * @return  the value of t_business_graduate_student_info.class_id
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public Integer getClassId() {
		return classId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.class_id
	 * @param classId  the value for t_business_graduate_student_info.class_id
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.no
	 * @return  the value of t_business_graduate_student_info.no
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.no
	 * @param no  the value for t_business_graduate_student_info.no
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setNo(String no) {
		this.no = no == null ? null : no.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.name
	 * @return  the value of t_business_graduate_student_info.name
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.name
	 * @param name  the value for t_business_graduate_student_info.name
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.birthday
	 * @return  the value of t_business_graduate_student_info.birthday
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.birthday
	 * @param birthday  the value for t_business_graduate_student_info.birthday
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.identity_num
	 * @return  the value of t_business_graduate_student_info.identity_num
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getIdentityNum() {
		return identityNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.identity_num
	 * @param identityNum  the value for t_business_graduate_student_info.identity_num
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setIdentityNum(String identityNum) {
		this.identityNum = identityNum == null ? null : identityNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.sex
	 * @return  the value of t_business_graduate_student_info.sex
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.sex
	 * @param sex  the value for t_business_graduate_student_info.sex
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setSex(String sex) {
		this.sex = sex == null ? null : sex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.nationality
	 * @return  the value of t_business_graduate_student_info.nationality
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getNationality() {
		return nationality;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.nationality
	 * @param nationality  the value for t_business_graduate_student_info.nationality
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setNationality(String nationality) {
		this.nationality = nationality == null ? null : nationality.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.work_unit
	 * @return  the value of t_business_graduate_student_info.work_unit
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getWorkUnit() {
		return workUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.work_unit
	 * @param workUnit  the value for t_business_graduate_student_info.work_unit
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setWorkUnit(String workUnit) {
		this.workUnit = workUnit == null ? null : workUnit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.contact_num1
	 * @return  the value of t_business_graduate_student_info.contact_num1
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getContactNum1() {
		return contactNum1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.contact_num1
	 * @param contactNum1  the value for t_business_graduate_student_info.contact_num1
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setContactNum1(String contactNum1) {
		this.contactNum1 = contactNum1 == null ? null : contactNum1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.contact_num2
	 * @return  the value of t_business_graduate_student_info.contact_num2
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getContactNum2() {
		return contactNum2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.contact_num2
	 * @param contactNum2  the value for t_business_graduate_student_info.contact_num2
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setContactNum2(String contactNum2) {
		this.contactNum2 = contactNum2 == null ? null : contactNum2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.email
	 * @return  the value of t_business_graduate_student_info.email
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.email
	 * @param email  the value for t_business_graduate_student_info.email
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.qq
	 * @return  the value of t_business_graduate_student_info.qq
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.qq
	 * @param qq  the value for t_business_graduate_student_info.qq
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setQq(String qq) {
		this.qq = qq == null ? null : qq.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.invoice_title
	 * @return  the value of t_business_graduate_student_info.invoice_title
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getInvoiceTitle() {
		return invoiceTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.invoice_title
	 * @param invoiceTitle  the value for t_business_graduate_student_info.invoice_title
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setInvoiceTitle(String invoiceTitle) {
		this.invoiceTitle = invoiceTitle == null ? null : invoiceTitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.study_status
	 * @return  the value of t_business_graduate_student_info.study_status
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getStudyStatus() {
		return studyStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.study_status
	 * @param studyStatus  the value for t_business_graduate_student_info.study_status
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setStudyStatus(String studyStatus) {
		this.studyStatus = studyStatus == null ? null : studyStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.teacher_id
	 * @return  the value of t_business_graduate_student_info.teacher_id
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public Integer getTeacherId() {
		return teacherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.teacher_id
	 * @param teacherId  the value for t_business_graduate_student_info.teacher_id
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.perform_teacher_id
	 * @return  the value of t_business_graduate_student_info.perform_teacher_id
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public Integer getPerformTeacherId() {
		return performTeacherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.perform_teacher_id
	 * @param performTeacherId  the value for t_business_graduate_student_info.perform_teacher_id
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setPerformTeacherId(Integer performTeacherId) {
		this.performTeacherId = performTeacherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.mentor_confirmation
	 * @return  the value of t_business_graduate_student_info.mentor_confirmation
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getMentorConfirmation() {
		return mentorConfirmation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.mentor_confirmation
	 * @param mentorConfirmation  the value for t_business_graduate_student_info.mentor_confirmation
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setMentorConfirmation(String mentorConfirmation) {
		this.mentorConfirmation = mentorConfirmation == null ? null
				: mentorConfirmation.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.remark
	 * @return  the value of t_business_graduate_student_info.remark
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.remark
	 * @param remark  the value for t_business_graduate_student_info.remark
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.conform_training_plan_yn
	 * @return  the value of t_business_graduate_student_info.conform_training_plan_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getConformTrainingPlanYn() {
		return conformTrainingPlanYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.conform_training_plan_yn
	 * @param conformTrainingPlanYn  the value for t_business_graduate_student_info.conform_training_plan_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setConformTrainingPlanYn(String conformTrainingPlanYn) {
		this.conformTrainingPlanYn = conformTrainingPlanYn == null ? null
				: conformTrainingPlanYn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.conform_training_plan_info
	 * @return  the value of t_business_graduate_student_info.conform_training_plan_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getConformTrainingPlanInfo() {
		return conformTrainingPlanInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.conform_training_plan_info
	 * @param conformTrainingPlanInfo  the value for t_business_graduate_student_info.conform_training_plan_info
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setConformTrainingPlanInfo(String conformTrainingPlanInfo) {
		this.conformTrainingPlanInfo = conformTrainingPlanInfo == null ? null
				: conformTrainingPlanInfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.submit_professional_english_yn
	 * @return  the value of t_business_graduate_student_info.submit_professional_english_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getSubmitProfessionalEnglishYn() {
		return submitProfessionalEnglishYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.submit_professional_english_yn
	 * @param submitProfessionalEnglishYn  the value for t_business_graduate_student_info.submit_professional_english_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setSubmitProfessionalEnglishYn(
			String submitProfessionalEnglishYn) {
		this.submitProfessionalEnglishYn = submitProfessionalEnglishYn == null ? null
				: submitProfessionalEnglishYn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.submit_opening_report_yn
	 * @return  the value of t_business_graduate_student_info.submit_opening_report_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getSubmitOpeningReportYn() {
		return submitOpeningReportYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.submit_opening_report_yn
	 * @param submitOpeningReportYn  the value for t_business_graduate_student_info.submit_opening_report_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setSubmitOpeningReportYn(String submitOpeningReportYn) {
		this.submitOpeningReportYn = submitOpeningReportYn == null ? null
				: submitOpeningReportYn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.submit_frontier_lecture_yn
	 * @return  the value of t_business_graduate_student_info.submit_frontier_lecture_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getSubmitFrontierLectureYn() {
		return submitFrontierLectureYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.submit_frontier_lecture_yn
	 * @param submitFrontierLectureYn  the value for t_business_graduate_student_info.submit_frontier_lecture_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setSubmitFrontierLectureYn(String submitFrontierLectureYn) {
		this.submitFrontierLectureYn = submitFrontierLectureYn == null ? null
				: submitFrontierLectureYn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.pay_tuition_yn
	 * @return  the value of t_business_graduate_student_info.pay_tuition_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getPayTuitionYn() {
		return payTuitionYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.pay_tuition_yn
	 * @param payTuitionYn  the value for t_business_graduate_student_info.pay_tuition_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setPayTuitionYn(String payTuitionYn) {
		this.payTuitionYn = payTuitionYn == null ? null : payTuitionYn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.need_pay_amount
	 * @return  the value of t_business_graduate_student_info.need_pay_amount
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public Integer getNeedPayAmount() {
		return needPayAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.need_pay_amount
	 * @param needPayAmount  the value for t_business_graduate_student_info.need_pay_amount
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setNeedPayAmount(Integer needPayAmount) {
		this.needPayAmount = needPayAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.pass_paper_review_yn
	 * @return  the value of t_business_graduate_student_info.pass_paper_review_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getPassPaperReviewYn() {
		return passPaperReviewYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.pass_paper_review_yn
	 * @param passPaperReviewYn  the value for t_business_graduate_student_info.pass_paper_review_yn
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setPassPaperReviewYn(String passPaperReviewYn) {
		this.passPaperReviewYn = passPaperReviewYn == null ? null
				: passPaperReviewYn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_business_graduate_student_info.reply_status
	 * @return  the value of t_business_graduate_student_info.reply_status
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public String getReplyStatus() {
		return replyStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_business_graduate_student_info.reply_status
	 * @param replyStatus  the value for t_business_graduate_student_info.reply_status
	 * @mbggenerated  Wed Jul 22 16:44:30 GMT+08:00 2015
	 */
	public void setReplyStatus(String replyStatus) {
		this.replyStatus = replyStatus == null ? null : replyStatus.trim();
	}
}