package com.core.BasicInformation.dao;

import com.core.BasicInformation.model.ClassInfo;
import com.core.BasicInformation.model.ClassInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ClassInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	int countByExample(ClassInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	int deleteByExample(ClassInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	int insert(ClassInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	int insertSelective(ClassInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	List<ClassInfo> selectByExample(ClassInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	ClassInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ClassInfo record,
			@Param("example") ClassInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	int updateByExample(@Param("record") ClassInfo record,
			@Param("example") ClassInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	int updateByPrimaryKeySelective(ClassInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_business_class
	 * @mbggenerated  Thu Dec 24 21:01:52 CST 2015
	 */
	int updateByPrimaryKey(ClassInfo record);
}