package com.core.BasicInformation.dao;

import com.core.BasicInformation.model.VUserProfessor;
import com.core.BasicInformation.model.VUserProfessorExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface VUserProfessorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_professor_info
     *
     * @mbggenerated Mon Jul 27 10:36:34 GMT+08:00 2015
     */
    int countByExample(VUserProfessorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_professor_info
     *
     * @mbggenerated Mon Jul 27 10:36:34 GMT+08:00 2015
     */
    int deleteByExample(VUserProfessorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_professor_info
     *
     * @mbggenerated Mon Jul 27 10:36:34 GMT+08:00 2015
     */
    int insert(VUserProfessor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_professor_info
     *
     * @mbggenerated Mon Jul 27 10:36:34 GMT+08:00 2015
     */
    int insertSelective(VUserProfessor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_professor_info
     *
     * @mbggenerated Mon Jul 27 10:36:34 GMT+08:00 2015
     */
    List<VUserProfessor> selectByExample(VUserProfessorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_professor_info
     *
     * @mbggenerated Mon Jul 27 10:36:34 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") VUserProfessor record, @Param("example") VUserProfessorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_professor_info
     *
     * @mbggenerated Mon Jul 27 10:36:34 GMT+08:00 2015
     */
    int updateByExample(@Param("record") VUserProfessor record, @Param("example") VUserProfessorExample example);
}