package com.core.BasicInformation.dao;

import com.core.BasicInformation.model.VUserExpert;
import com.core.BasicInformation.model.VUserExpertExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface VUserExpertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_expert_info
     *
     * @mbggenerated Wed Aug 26 16:58:07 CST 2015
     */
    int countByExample(VUserExpertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_expert_info
     *
     * @mbggenerated Wed Aug 26 16:58:07 CST 2015
     */
    int deleteByExample(VUserExpertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_expert_info
     *
     * @mbggenerated Wed Aug 26 16:58:07 CST 2015
     */
    int insert(VUserExpert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_expert_info
     *
     * @mbggenerated Wed Aug 26 16:58:07 CST 2015
     */
    int insertSelective(VUserExpert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_expert_info
     *
     * @mbggenerated Wed Aug 26 16:58:07 CST 2015
     */
    List<VUserExpert> selectByExample(VUserExpertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_expert_info
     *
     * @mbggenerated Wed Aug 26 16:58:07 CST 2015
     */
    int updateByExampleSelective(@Param("record") VUserExpert record, @Param("example") VUserExpertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_expert_info
     *
     * @mbggenerated Wed Aug 26 16:58:07 CST 2015
     */
    int updateByExample(@Param("record") VUserExpert record, @Param("example") VUserExpertExample example);
}