package com.core.system.dao;

import com.core.system.model.Log;
import com.core.system.model.LogExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_logdata
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    int countByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_logdata
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    int deleteByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_logdata
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_logdata
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_logdata
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    int insertSelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_logdata
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    List<Log> selectByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_logdata
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    Log selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_logdata
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    int updateByExampleSelective(@Param("record") Log record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_logdata
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    int updateByExample(@Param("record") Log record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_logdata
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    int updateByPrimaryKeySelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_logdata
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    int updateByPrimaryKey(Log record);
}