package com.core.system.model;

public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_logdata.id
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_logdata.user
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_logdata.ip
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_logdata.date
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_logdata.action
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_logdata.module
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    private String module;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_logdata.discription
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    private String discription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_logdata.id
     *
     * @return the value of t_security_logdata.id
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_logdata.id
     *
     * @param id the value for t_security_logdata.id
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_logdata.user
     *
     * @return the value of t_security_logdata.user
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_logdata.user
     *
     * @param user the value for t_security_logdata.user
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_logdata.ip
     *
     * @return the value of t_security_logdata.ip
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_logdata.ip
     *
     * @param ip the value for t_security_logdata.ip
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_logdata.date
     *
     * @return the value of t_security_logdata.date
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_logdata.date
     *
     * @param date the value for t_security_logdata.date
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_logdata.action
     *
     * @return the value of t_security_logdata.action
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_logdata.action
     *
     * @param action the value for t_security_logdata.action
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_logdata.module
     *
     * @return the value of t_security_logdata.module
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_logdata.module
     *
     * @param module the value for t_security_logdata.module
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_logdata.discription
     *
     * @return the value of t_security_logdata.discription
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    public String getDiscription() {
        return discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_logdata.discription
     *
     * @param discription the value for t_security_logdata.discription
     *
     * @mbggenerated Sat Nov 02 17:38:12 CST 2013
     */
    public void setDiscription(String discription) {
        this.discription = discription == null ? null : discription.trim();
    }
}